#include "biblio.h"

char *leituraMapa(int rand, int tamanho){
   
    char **mapas;

    tamanho *= tamanho;

    switch (tamanho){

    case 81:
        
        mapas = (char**) malloc(3*sizeof(char*));
        for(int i=0; i<3; i++){
            mapas[i] = (char*) malloc(82*sizeof(char));
        }

        mapas[0] = "CCCTCCCTSCBCCBCCCBCCCCCCCCCCCCCCCCBTCCCTACCCCCCCCCCCCCCCCCCBCCCCCTCCCCTCCCBCCCCBC";
        mapas[1] = "CTCCCCCCCBCCCCBCCCCCCCCCCTCTBCCCCCBCCCCCATCCSCTCCCCCCCBCCBCCCCBCCCCCCTCCCCCCCCBCC";
        mapas[2] = "CTCCCCBCCCCCBCCCCTCCCCTCCCCCCCCCCCBCCCBCACCCSCTCCTCCCCCCCCCCBCBCCCBCCTCCCCCCCCBCC";
        
        break;
    
    case 121:
       
        mapas = (char**) malloc(4*sizeof(char*));
        for(int i=0; i<4; i++){
            mapas[i] = (char*) malloc(122*sizeof(char));
        }

        mapas[0] = "CCBCCCCCCCCCCTCCCCBCTCCCTCCCCTCCCCBCCCCCCCBCCCCCCCCCCTCCCCCCACCCCBCCCCCCCCCCCCCCCTCCCCCCCCCCCCCCCCCCCTCCCCCCCSCCBCCCTBCCC";
        mapas[1] = "CCBCCCCCCCCCCCCCTCBCTCCCTCCCCTCCCCCCCCCCCCBCCCBCCCCCCTCCCCCCACCCCBCCCCCCCCCCCCCCCTCCCCCCCCCCCCCCCCCCCTCCCCCCCSCCBCCCTBCCC";
        mapas[2] = "CBCCCCCCCCCCCCCCTCCCTCTCCCCCBTCCCCCCCCCCCCBSCCBCCCCCCTCCCCCCACCCCCCCCCCCCCCCCCCCCBCTCCCCCCCCCCCCCCCCCTCCCCCCCCCCBCCCBTCCC";
        mapas[3] = "CCCCCCCCCCCCCCCBTCCCCCCCCCCTCCBTCCCCCCCCCCCCCCCCCCCCCCCCCBCCACCCCCCCTCCCBTCBTCCCCCCCCCCCCCCCCCCCCCSCCTCCCCCCCCCCBCCCBTCCC";


        break;

    case 256:
        
        mapas = (char**) malloc(3*sizeof(char*));
        for(int i=0; i<3; i++){
            mapas[i] = (char*) malloc(257*sizeof(char));
        }

        mapas[0] = "BCCCCCCCCCBCCCCBCTCCCCTCCCCTCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCCBCCCCCCCCTCCCCCCCCCCCBCCCCCTCCCCCCCCCTCCCCCCCCCCCCCCCACCCCCCCCCBCCCCCCCTCCCTCCCTCCCCCCCCCCCCCBCCCCCCBCCCCCCCCCCCCCCCCTCCCBCCCCCCCCCCCCCCCCCCCCCCTCCTCCCCCCCCCSCCBCCCCBCCCCCCCC";
        mapas[1] = "BCCCCCTCCCCCCCBCCTCCCCCCCCCCCCCCCCCCCBCCCCCCCCCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCCBCCCCCCCCTCCCCCCCCCCCBCCCCCCCSCCCCCCCTCCCCCCCCCCCCCCCACCCCCCCCCBCCCCCCCTCCCCCTCTCCCCCCCCCCCCCBCCCCCBCCCCCCCCTCCCCCCTCCCCCCCCCCCTCCCCCCCCBCCCCCCCBCCCCCCCCCCCCCCCCCCCTBCCCCCCCC";
        mapas[2] = "CCCCCCCCCCCCCCBCCCBCCCCCCCCCCCCTCCCCCTCCCCCCCCCCCCCCCCCBCCCCCCCCCCTCCCCCCCCCBCCCCCBCCCCCCCCTCCCCCCCCCCBCCCCCCCCCCCCCCCCCCTCCCCCCCCCCCCCACCCCCCCCCBCCTCCCCCCCCCCCCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCCBTCCCCCBCCTCCCCCCCCCCCCCCCCBCCCCCCCTCCCCCTSTCCCCCBCCCCCCCCC";


        break;

    default:
        exit(1);
        break;
    }  

    return mapas[rand];
}